import type { Opportunity } from "../_types/commercial";

/**
 * Todas as oportunidades comerciais do Somma Club.
 * Fonte única para a tabela geral, filtros, modais, comparador e simulador.
 * Valores sempre "a partir de". Editar aqui atualiza a apresentação inteira.
 */
export const OPPORTUNITIES: Opportunity[] = [
  /* ── Ativações presenciais ─────────────────────────────────────────── */
  {
    id: "ativacao-sabado",
    nome: "Ativação em um sábado",
    filtros: ["Presencial"],
    tipo: "Presencial",
    investimento: 5000,
    unidade: "único",
    investimentoLabel: "A partir de R$ 5.000",
    duracao: "Um encontro",
    publicoPotencial: "Entre 200 e 350 participantes",
    descricao:
      "Presença da marca em um encontro semanal do Somma Club, com espaço para ativação e contato direto com a comunidade.",
    objetivo: "Testar uma ativação, apresentar um produto ou criar um primeiro contato com a comunidade.",
    indicacao:
      "Marcas que desejam testar uma ativação, apresentar um produto ou criar um primeiro contato com a comunidade.",
    entregas: [
      "Espaço para ativação",
      "Exposição da identidade da marca",
      "Distribuição de produtos e amostras",
      "Experimentação e degustação",
      "Avaliações e demonstrações",
      "Benefícios para participantes",
      "QR Code, pesquisa e cadastro consentido",
      "Conteúdo da ativação",
    ],
    naoIncluido: [
      "Estrutura física, tenda e mobiliário",
      "Equipe do parceiro",
      "Produtos, amostras e brindes",
      "Equipamentos e licenças especiais",
      "Produção externa",
    ],
    observacoes: "Itens de estrutura e produção podem ser orçados separadamente.",
    atributos: { presencaFisica: 2, midiaDigital: 0, comunicacaoBase: 1, tecnologia: 1, exclusividade: 0, personalizacao: 1, relatorios: 1 },
  },
  {
    id: "ativacao-tres-sabados",
    nome: "Ativação em três sábados do mês",
    filtros: ["Presencial"],
    tipo: "Presencial",
    investimento: 12000,
    unidade: "único",
    investimentoLabel: "A partir de R$ 12.000",
    duracao: "Três encontros",
    publicoPotencial: "De 600 a 1.050 participações acumuladas",
    descricao: "Presença recorrente da marca em três encontros do mesmo mês.",
    objetivo: "Aumentar frequência, lembrança, experimentação e relacionamento.",
    indicacao: "Marcas que precisam aumentar frequência, lembrança, experimentação e relacionamento.",
    entregas: [
      "Planejamento das ativações",
      "Comunicação prévia",
      "Presença física recorrente",
      "Experimentação recorrente",
      "Benefício exclusivo",
      "QR Code e cadastro consentido",
      "Registro das ações",
      "Relatório consolidado",
    ],
    naoIncluido: [
      "Estrutura física, tenda e mobiliário",
      "Produtos, amostras e brindes",
      "Equipamentos, licenças e produção externa",
    ],
    observacoes: "Itens de estrutura e produção podem ser orçados separadamente.",
    atributos: { presencaFisica: 2, midiaDigital: 1, comunicacaoBase: 1, tecnologia: 1, exclusividade: 0, personalizacao: 2, relatorios: 2 },
  },
  {
    id: "mes-somma-day",
    nome: "Ativação no mês inteiro mais Somma Day",
    filtros: ["Presencial", "Digital"],
    tipo: "Presencial e digital",
    investimento: 20000,
    unidade: "único",
    investimentoLabel: "A partir de R$ 20.000",
    duracao: "Encontros do mês e Somma Day",
    publicoPotencial: "Todos os encontros do mês + Somma Day",
    descricao:
      "Presença nos encontros semanais do mês e participação especial no Somma Day. O Somma Day é o principal encontro mensal da comunidade, com programação ampliada, maior concentração de participantes, experiências, parceiros, entretenimento, conteúdo e ativações especiais.",
    objetivo: "Construir uma narrativa durante o mês e encerrar o ciclo com uma experiência de maior impacto.",
    indicacao:
      "Marcas que desejam construir uma narrativa durante o mês e encerrar o ciclo com uma experiência de maior impacto.",
    entregas: [
      "Campanha de aquecimento",
      "Ativações semanais",
      "Presença no Somma Day",
      "Experiência de marca",
      "Conteúdo",
      "Benefício para a comunidade",
      "Comunicação digital",
      "Relatório de entregas",
    ],
    naoIncluido: [
      "Estrutura física, tenda e mobiliário",
      "Produtos, amostras e brindes",
      "Equipamentos, licenças e produção externa",
    ],
    observacoes: "O Somma Day tem programação ampliada e maior concentração de público.",
    atributos: { presencaFisica: 2, midiaDigital: 2, comunicacaoBase: 2, tecnologia: 1, exclusividade: 0, personalizacao: 2, relatorios: 2 },
  },

  /* ── Mídia no Instagram ────────────────────────────────────────────── */
  {
    id: "instagram-stories",
    nome: "Instagram Stories",
    filtros: ["Digital"],
    tipo: "Digital",
    investimento: 2500,
    unidade: "único",
    investimentoLabel: "A partir de R$ 2.500",
    duracao: "Conforme escopo",
    descricao:
      "Campanha divulgada nos Stories do Somma Club. Pode incluir sequência de Stories, marcação do parceiro, link, chamada para ação, benefício, convite ou cobertura.",
    objetivo: "Comunicar campanhas pontuais e gerar tráfego com frequência e relacionamento.",
    indicacao:
      "Campanhas pontuais, lançamentos, inscrições, benefícios, geração de tráfego e comunicação de ativações.",
    entregas: [
      "Sequência de Stories",
      "Marcação do parceiro",
      "Link e chamada para ação",
      "Comunicação de benefício, convite ou cobertura",
    ],
    observacoes: "A quantidade de Stories, período e produção devem ser definidos no escopo.",
    atributos: { presencaFisica: 0, midiaDigital: 2, comunicacaoBase: 0, tecnologia: 0, exclusividade: 0, personalizacao: 1, relatorios: 1 },
  },
  {
    id: "instagram-completo",
    nome: "Instagram completo",
    filtros: ["Digital"],
    tipo: "Digital",
    investimento: 6000,
    unidade: "único",
    investimentoLabel: "A partir de R$ 6.000",
    duracao: "Conforme escopo",
    descricao:
      "Campanha integrada para combinar frequência, posicionamento e descoberta, nos formatos Stories, Feed e Reels.",
    objetivo: "Combinar frequência (Stories), posicionamento (Feed) e descoberta (Reels).",
    indicacao: "Marcas que querem uma presença digital integrada e consistente no perfil do Somma.",
    entregas: [
      "Planejamento editorial",
      "Produção",
      "Publicação em Stories, Feed e Reels",
      "Marcação e chamada para ação",
      "Relatório dos resultados disponíveis",
    ],
    observacoes: "Os formatos e volumes exatos são definidos no escopo.",
    atributos: { presencaFisica: 0, midiaDigital: 2, comunicacaoBase: 0, tecnologia: 0, exclusividade: 0, personalizacao: 2, relatorios: 2 },
  },

  /* ── Base própria ──────────────────────────────────────────────────── */
  {
    id: "disparo-email",
    nome: "Disparo de e-mail",
    filtros: ["Base de dados"],
    tipo: "Base própria",
    investimento: 2000,
    unidade: "por disparo",
    investimentoLabel: "A partir de R$ 2.000 por disparo",
    duracao: "Por disparo",
    descricao: "Envio de campanha para a base cadastrada do Somma Club.",
    objetivo: "Comunicar diretamente com a base própria para lançamentos, benefícios e captação.",
    indicacao:
      "Lançamentos, inscrições, benefícios, pesquisas, cupons, agendamentos, páginas de captura, convites, conteúdo educativo e direcionamento para WhatsApp.",
    entregas: [
      "Campanha enviada para a base cadastrada",
      "Direcionamento para landing page, formulário ou WhatsApp",
      "Comunicação de benefício, cupom ou convite",
    ],
    observacoes:
      "Segmentações e automações mais complexas podem alterar o investimento. A base permanece sob gestão do Somma Club.",
    atributos: { presencaFisica: 0, midiaDigital: 1, comunicacaoBase: 2, tecnologia: 1, exclusividade: 0, personalizacao: 1, relatorios: 1 },
  },

  /* ── Tecnologia / mídia própria ────────────────────────────────────── */
  {
    id: "agenda-somma",
    nome: "Agenda Somma Club",
    filtros: ["Tecnologia"],
    tipo: "Tecnologia",
    investimento: 1500,
    unidade: "por mês",
    investimentoLabel: "A partir de R$ 1.500 por mês",
    duracao: "Mensal",
    descricao:
      "A Agenda Somma Club é uma plataforma própria que organiza e divulga encontros, eventos, experiências, campanhas e oportunidades relevantes para a comunidade. A empresa pode ser inserida como parceira de uma atividade, benefício ou experiência.",
    objetivo: "Ocupar um espaço dentro da rotina da comunidade, e não apenas uma publicação isolada.",
    indicacao: "Marcas que querem presença recorrente e útil no dia a dia da comunidade.",
    entregas: [
      "Nome da ação, descrição, data, horário e local",
      "Imagem e identidade visual",
      "Condição exclusiva",
      "Link de inscrição, link de compra e botão de WhatsApp",
      "Landing page e informações complementares",
    ],
    observacoes: "A marca passa a ocupar um espaço na rotina da comunidade, não apenas uma publicação isolada.",
    atributos: { presencaFisica: 0, midiaDigital: 1, comunicacaoBase: 1, tecnologia: 2, exclusividade: 0, personalizacao: 1, relatorios: 1 },
  },
  {
    id: "popup-site",
    nome: "Pop-up no site",
    filtros: ["Tecnologia"],
    tipo: "Tecnologia",
    investimento: 2500,
    unidade: "por até 15 dias",
    investimentoLabel: "A partir de R$ 2.500 por até 15 dias",
    duracao: "Até 15 dias",
    descricao: "Comunicação exibida em destaque para os visitantes do site.",
    objetivo: "Direcionar os visitantes do site para uma ação específica da marca.",
    indicacao: "Campanhas com destino claro: landing page, formulário, e-commerce, cupom ou benefício.",
    entregas: [
      "Pop-up em destaque no sommaclub.com.br",
      "Direcionamento para landing page, formulário ou WhatsApp",
      "Direcionamento para e-commerce, página promocional ou cupom",
    ],
    observacoes: "Período de até 15 dias por ativação.",
    atributos: { presencaFisica: 0, midiaDigital: 1, comunicacaoBase: 0, tecnologia: 2, exclusividade: 0, personalizacao: 1, relatorios: 1 },
  },
  {
    id: "popup-checkin",
    nome: "Pop-up na área de check-in",
    filtros: ["Tecnologia"],
    tipo: "Tecnologia",
    investimento: 3500,
    unidade: "por até 15 dias",
    investimentoLabel: "A partir de R$ 3.500 por até 15 dias",
    duracao: "Até 15 dias",
    descricao:
      "Comunicação exibida durante a jornada de check-in dos participantes. Impacta diretamente pessoas que estão confirmando participação em uma atividade do Somma Club.",
    objetivo: "Impactar diretamente quem está confirmando participação em uma atividade.",
    indicacao: "Cupom, pesquisa, benefício, convite, campanha, cadastro, lançamento e chamada para ativação presencial.",
    entregas: [
      "Pop-up durante a jornada de check-in",
      "Impacto direto no público presencial",
      "Cupom, pesquisa, benefício ou convite",
      "Chamada para ativação presencial",
    ],
    observacoes: "Período de até 15 dias por ativação.",
    atributos: { presencaFisica: 1, midiaDigital: 1, comunicacaoBase: 1, tecnologia: 2, exclusividade: 0, personalizacao: 1, relatorios: 1 },
  },

  /* ── Patrocínios recorrentes ───────────────────────────────────────── */
  {
    id: "patrocinio-3-meses",
    nome: "Patrocínio por três meses",
    filtros: ["Patrocínio"],
    tipo: "Recorrente",
    investimento: 12000,
    unidade: "por mês",
    investimentoLabel: "A partir de R$ 12.000 por mês",
    duracao: "Três meses",
    descricao: "Patrocínio recorrente por três meses (total a partir de R$ 36.000).",
    objetivo: "Sustentar lançamentos, campanhas sazonais e projetos com duração definida.",
    indicacao: "Lançamentos, campanhas sazonais e projetos com duração definida.",
    entregas: [
      "Mídia digital",
      "Ativações presenciais",
      "Agenda Somma Club",
      "Comunicação com a base",
      "Mídia no site",
      "Benefícios",
      "Conteúdo",
      "Relatórios",
    ],
    observacoes: "Total a partir de R$ 36.000. Os valores mensais reduzidos estão condicionados à contratação integral do período.",
    atributos: { presencaFisica: 2, midiaDigital: 2, comunicacaoBase: 2, tecnologia: 2, exclusividade: 0, personalizacao: 2, relatorios: 2 },
  },
  {
    id: "patrocinio-6-meses",
    nome: "Patrocínio por seis meses",
    filtros: ["Patrocínio"],
    tipo: "Recorrente",
    investimento: 10000,
    unidade: "por mês",
    investimentoLabel: "A partir de R$ 10.000 por mês",
    duracao: "Seis meses",
    descricao: "Patrocínio recorrente por seis meses (total a partir de R$ 60.000).",
    objetivo: "Construir recorrência, reconhecimento e relacionamento contínuo.",
    indicacao: "Construção de recorrência, reconhecimento e relacionamento contínuo.",
    entregas: [
      "Calendário semestral",
      "Ativações",
      "Conteúdo",
      "Mídia",
      "Presença física",
      "Agenda",
      "Benefícios",
      "Relatórios periódicos",
    ],
    observacoes: "Total a partir de R$ 60.000. Os valores mensais reduzidos estão condicionados à contratação integral do período.",
    atributos: { presencaFisica: 2, midiaDigital: 2, comunicacaoBase: 2, tecnologia: 2, exclusividade: 0, personalizacao: 2, relatorios: 2 },
  },
  {
    id: "patrocinio-12-meses",
    nome: "Patrocínio por doze meses",
    filtros: ["Patrocínio"],
    tipo: "Recorrente",
    investimento: 8000,
    unidade: "por mês",
    investimentoLabel: "A partir de R$ 8.000 por mês",
    duracao: "Doze meses",
    descricao: "Patrocínio recorrente por doze meses (total a partir de R$ 96.000).",
    objetivo: "Presença contínua e construção de marca no longo prazo.",
    indicacao: "Presença contínua e construção de marca no longo prazo.",
    entregas: [
      "Calendário anual",
      "Presença institucional",
      "Campanhas digitais",
      "Ativações presenciais",
      "Conteúdo colaborativo",
      "Agenda e site",
      "Benefícios",
      "Relatórios e planejamento periódico",
    ],
    observacoes: "Total a partir de R$ 96.000. Os valores mensais reduzidos estão condicionados à contratação integral do período.",
    atributos: { presencaFisica: 2, midiaDigital: 2, comunicacaoBase: 2, tecnologia: 2, exclusividade: 1, personalizacao: 2, relatorios: 2 },
  },

  /* ── Assessoria Somma Club ─────────────────────────────────────────── */
  {
    id: "midia-assessoria",
    nome: "Ação de mídia na Assessoria Somma Club",
    filtros: ["Assessoria"],
    tipo: "Assessoria",
    investimento: 3000,
    unidade: "por mês",
    investimentoLabel: "A partir de R$ 3.000 por mês",
    duracao: "Mensal",
    descricao: "Comunicação direcionada aos alunos e participantes da assessoria.",
    objetivo: "Falar com um público focado em performance, saúde e qualidade de vida.",
    indicacao: "Saúde, nutrição, performance, equipamentos, recuperação, serviços e qualidade de vida.",
    entregas: [
      "Conteúdos e campanhas",
      "Benefícios e ações educativas",
      "Inserções em canais da assessoria",
      "Comunicações relacionadas a performance e saúde",
    ],
    atributos: { presencaFisica: 1, midiaDigital: 1, comunicacaoBase: 1, tecnologia: 0, exclusividade: 0, personalizacao: 1, relatorios: 1 },
  },
  {
    id: "patrocinio-assessoria",
    nome: "Patrocínio da Assessoria Somma Club",
    filtros: ["Assessoria", "Patrocínio"],
    tipo: "Assessoria",
    investimento: 8000,
    unidade: "por mês",
    investimentoLabel: "A partir de R$ 8.000 por mês",
    duracao: "Mensal",
    descricao: "A empresa ocupa uma posição oficial dentro da assessoria esportiva.",
    objetivo: "Associar a marca à performance e ao acompanhamento esportivo do Somma.",
    indicacao: "Marcas de saúde, performance e lifestyle que buscam vínculo com alunos e treinos.",
    entregas: [
      "Presença nos canais",
      "Marca em materiais selecionados",
      "Ativações em treinos",
      "Conteúdos especializados",
      "Benefícios para alunos",
      "Desafios e jornadas esportivas",
      "Campanhas de relacionamento",
      "Presença em eventos da assessoria",
    ],
    atributos: { presencaFisica: 2, midiaDigital: 1, comunicacaoBase: 1, tecnologia: 0, exclusividade: 1, personalizacao: 2, relatorios: 2 },
  },

  /* ── Institucional / exclusividade ─────────────────────────────────── */
  {
    id: "patrocinador-oficial",
    nome: "Patrocinador oficial",
    filtros: ["Patrocínio"],
    tipo: "Institucional",
    investimento: 15000,
    unidade: "por mês",
    investimentoLabel: "A partir de R$ 15.000 por mês",
    duracao: "Mensal",
    descricao: "A empresa passa a integrar oficialmente o ecossistema Somma Club.",
    objetivo: "Presença institucional contínua com exposição nos principais canais.",
    indicacao: "Marcas que buscam presença institucional contínua e integrada ao ecossistema.",
    entregas: [
      "Presença institucional contínua",
      "Exposição nos principais canais",
      "Ativações programadas",
      "Participação nos encontros",
      "Mídia digital recorrente",
      "Agenda Somma Club",
      "Comunicação com a base",
      "Eventos proprietários",
      "Conteúdo colaborativo",
      "Relatórios de entrega",
    ],
    observacoes: "A composição exata depende do calendário, duração, categoria e escopo contratado.",
    destaque: true,
    atributos: { presencaFisica: 2, midiaDigital: 2, comunicacaoBase: 2, tecnologia: 2, exclusividade: 1, personalizacao: 2, relatorios: 2 },
  },
  {
    id: "patrocinio-exclusivo",
    nome: "Patrocínio exclusivo",
    filtros: ["Exclusividade", "Patrocínio"],
    tipo: "Exclusividade",
    investimento: 25000,
    unidade: "por mês",
    investimentoLabel: "A partir de R$ 25.000 por mês",
    duracao: "Mensal",
    descricao:
      "A empresa ocupa com exclusividade uma categoria comercial dentro do Somma Club (ex.: academia oficial, banco oficial, laboratório oficial, clínica, farmácia de manipulação, supermercado, marca esportiva, bebida, mobilidade ou recuperação oficial).",
    objetivo:
      "Garantir exclusividade de categoria: durante o período contratado, o Somma não fecha uma propriedade equivalente com um concorrente direto da categoria definida.",
    indicacao: "Marcas que querem ser a referência única de uma categoria dentro do Somma.",
    entregas: [
      "Exclusividade de categoria durante o contrato",
      "Presença institucional contínua",
      "Ativações e mídia recorrentes",
      "Agenda, site e comunicação com a base",
      "Conteúdo colaborativo",
      "Relatórios de entrega",
    ],
    naoIncluido: [
      "A exclusividade precisa de categoria bem definida e prazo determinado",
      "Limites de entrega e regras para eventos externos",
      "Regras para campanhas já existentes",
    ],
    observacoes:
      "A exclusividade exige categoria bem definida, prazo determinado, limites de entrega, regras para eventos externos, regras para campanhas já existentes e condições comerciais específicas.",
    destaque: true,
    atributos: { presencaFisica: 2, midiaDigital: 2, comunicacaoBase: 2, tecnologia: 2, exclusividade: 2, personalizacao: 2, relatorios: 2 },
  },
];

/** Acesso rápido por id. */
export function getOpportunity(id: string): Opportunity | undefined {
  return OPPORTUNITIES.find((o) => o.id === id);
}

/** Ativações presenciais oferecidas como base do simulador. */
export const SIMULATOR_ACTIVATIONS = [
  "ativacao-sabado",
  "ativacao-tres-sabados",
  "mes-somma-day",
  "patrocinador-oficial",
];
